version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - '3306:3306'
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - backend

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - '8082:8080' # Adminer will be accessible on http://localhost:8080
    depends_on:
      - mysql
    environment:
      - ADMINER_DEFAULT_SERVER=mysql
    networks:
      - backend

  redis:
    image: redis:6.0.7
    container_name: redis
    restart: always
    volumes:
      - redis:/data
    ports:
      - 6379:6379
    networks:
      - backend

  redis_insight:
    image: redislabs/redisinsight
    container_name: redis_insight
    restart: always
    depends_on:
      - redis
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - 5540:5540
    volumes:
      - redis:/db
    networks:
      - backend

volumes:
  mysql:
  redis:

networks:
  backend:
    driver: bridge
